run: Fix CUDA 13 '-DNVPTX_RUN_INCLUDE_SYSTEM_CUDA_H' build
In CUDA 13, the 'cuCtxCreate' API (internally switched to 'cuCtxCreate_v4',
and) changed from:

    CUresult cuCtxCreate (CUcontext *, unsigned int, CUdevice);

... to:

    CUresult cuCtxCreate (CUcontext *, CUctxCreateParams *, unsigned int, CUdevice);

..., causing:

    [...]/nvptx-run.cc: In function ‘int main(int, char**)’:
    [...]/nvptx-run.cc:251:6: error: too few arguments to function
      251 |   r = CUDA_CALL_NOCHECK (cuCtxCreate, &ctx, 0, dev);