nm: '#define __STDC_FORMAT_MACROS' for '#include <inttypes.h>' [#40]
Otherwise, may run into:

    [...]/nvptx-nm.cc: In function 'const char* get_print_format()':
    [...]/nvptx-nm.cc:445:22: error: 'PRIo64' was not declared in this scope
         case 8:  radix = PRIo64; break;
                          ^~~~~~
    [...]/nvptx-nm.cc:446:22: error: 'PRId64' was not declared in this scope
         case 10: radix = PRId64; break;
                          ^~~~~~
    [...]/nvptx-nm.cc:447:22: error: 'PRIx64' was not declared in this scope
         case 16: radix = PRIx64; break;
                          ^~~~~~

I've borrowed for 'nvptx-nm.cc' GCC's 'gcc/system.h' wording per
Subversion r210973 (Git commit 7ea7f668fc91fc3d08b389b1be38aa9b8cbca27c).

See also <https://stackoverflow.com/a/8132440>, for example.