ld: Global constructor/destructor support: Restore GCC 4.8 build
The recent commit 96f8fc59a757767b9e98157d95c21e9fef22a93b
"ld: Global constructor/destructor support" doesn't build with GCC 4.8:

    In file included from [GCC 4.8]/include/c++/algorithm:62:0,
                     from ../source-nvptx-tools/nvptx-ld.cc:35:
    [GCC 4.8]/include/c++/bits/stl_algo.h: In instantiation of '_RandomAccessIterator std::__unguarded_partition(_RandomAccessIterator, _RandomAccessIterator, const _Tp&, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<cdtor*, std::vector<cdtor> >; _Tp = cdtor; _Compare = cdtor::<anonymous class>]':
    [GCC 4.8]/include/c++/bits/stl_algo.h:2296:78:   required from '_RandomAccessIterator std::__unguarded_partition_pivot(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<cdtor*, std::vector<cdtor> >; _Compare = cdtor::<anonymous class>]'
    [GCC 4.8]/include/c++/bits/stl_algo.h:2337:62:   required from 'void std::__introsort_loop(_RandomAccessIterator, _RandomAccessIterator, _Size, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<cdtor*, std::vector<cdtor> >; _Size = long int; _Compare = cdtor::<anonymous class>]'
    [GCC 4.8]/include/c++/bits/stl_algo.h:5499:44:   required from 'void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter = __gnu_cxx::__normal_iterator<cdtor*, std::vector<cdtor> >; _Compare = cdtor::<anonymous class>]'
    ../source-nvptx-tools/nvptx-ld.cc:390:55:   required from here
    [GCC 4.8]/include/c++/bits/stl_algo.h:2263:35: error: no match for call to '(cdtor::<anonymous class>) (cdtor&, const cdtor&)'
        while (__comp(*__first, __pivot))
                                       ^
    ../source-nvptx-tools/nvptx-ld.cc:316:3: note: candidate is:
       {
       ^
    ../source-nvptx-tools/nvptx-ld.cc:318:10: note: bool cdtor::<anonymous class>::operator()(cdtor&, cdtor&) const
         bool operator() (cdtor &a, cdtor &b) const
              ^
    ../source-nvptx-tools/nvptx-ld.cc:318:10: note:   no known conversion for argument 2 from 'const cdtor' to 'cdtor&'
    In file included from [GCC 4.8]/include/c++/algorithm:62:0,
                     from ../source-nvptx-tools/nvptx-ld.cc:35:
    [GCC 4.8]/include/c++/bits/stl_algo.h:2266:34: error: no match for call to '(cdtor::<anonymous class>) (const cdtor&, cdtor&)'
        while (__comp(__pivot, *__last))
                                      ^
    ../source-nvptx-tools/nvptx-ld.cc:316:3: note: candidate is:
       {
       ^
    ../source-nvptx-tools/nvptx-ld.cc:318:10: note: bool cdtor::<anonymous class>::operator()(cdtor&, cdtor&) const
         bool operator() (cdtor &a, cdtor &b) const
              ^
    ../source-nvptx-tools/nvptx-ld.cc:318:10: note:   no known conversion for argument 1 from 'const cdtor' to 'cdtor&'
    make: *** [Makefile:64: nvptx-none-ld] Error 1

Fix this by const-qualifying the comparator's formal parameters.  (..., as it
should've been done anyway.)

Resolves #47 "nvptx-ld.cc: Improve C++11 compatibility with older compilers".